### ISSUE TITLE
Not redirected when not logged in

### ISSUE THREAD

**Issue by pyama86** [hackmdio/codimd#1118]
Hi team!
I have started hackmd with k8s and I am using google oauth2.

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hackmd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hackmd
    spec:
      containers:
        - name: app
          image: hackmdio/hackmd:1.2.1
          env:
          - name: HMD_DB_URL
            valueFrom:
              secretKeyRef:
                name: hackmd-secret
                key: mysql_url
          - name: CMD_GOOGLE_CLIENTID
            valueFrom:
              secretKeyRef:
                name: hackmd-secret
                key: google_client_id
          - name: CMD_GOOGLE_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: hackmd-secret
                key: google_client_secret
          - name: CMD_PROTOCOL_USESSL
            value: "true"
          - name: CMD_ALLOW_ANONYMOUS
            value: "false"
          - name: CMD_ALLOW_ANONYMOUS_EDITS
            value: "false"
          - name: CMD_ALLOW_FREEURL
            value: "false"
          - name: CMD_ALLOW_EMAIL_REGISTER
            value: "false"
          - name: CMD_EMAIL
            value: "false"
          - name: CMD_DEFAULT_PERMISSION
            value: "limited"
          ports:
          - containerPort: 3000
```

When you are not logged in, opening the note URL opens the screen shown below.

![image](https://user-images.githubusercontent.com/8022082/51098665-515aec00-180f-11e9-8fe5-98e6ec431080.png)

I guess this is probably because there are no variables passed to Express's Ridirect, but can I redirect correctly if I do something?
