### ISSUE TITLE
Using CMD_URL_PATH breaks codimd

### ISSUE THREAD

**Issue by Trolldemorted** [hackmdio/codimd#1149]
If I start this compose file:

```yaml
version: '3.4'

services:
  codimd:
    image: hackmdio/hackmd:1.2.1
    environment:
      - CMD_DB_URL=postgres://docker:docker@codimdpostgres:5432/hackmd
      - CMD_ALLOW_FREEURL=true
      - CMD_URL_PATH=teeeeeeeeeest
    ports:
      - "9002:3000"
  codimdpostgres:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: hackmd
```

codi breaks down completely (always offline, spams requests to /teeeeeeeeeest/teeeeeeeeeest). Is that configuration option suppsed to work? If not, could you remove it from the documentation?
