### ISSUE TITLE
serverURL still uses port 3000 instead of the remapped port of docker

### ISSUE THREAD

**Issue by frankyan** [hackmdio/codimd#1177]
Hi, I am using CodiMD with docker container on a Linux server. The server has a domain name `www.myserver.com`. So I set `CMD_DOMAIN=myserver.com`. The edited part of the compose file is shown below.
```
  app:
    image: hackmdio/hackmd:1.3.0
    environment:
      - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_DEFAULT_PERMISSION=locked
      - CMD_ALLOW_FREEURL=false
      - CMD_ALLOW_PDF_EXPORT=true
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_URL_ADDPORT=true
      - CMD_PROTOCOL_USESSL=false
      - CMD_DOMAIN=www.myserver.com
    ports:
        - "10001:3000"
  ```
I can access the index page of CodiMD by URL `http://www.myserver.com:10001`. But I cannot login or do other things. I inspected the index page and found that it's trying to fetch things on server using generated URL with prot 3000. For example, the index page cannot display the CodiMD screenshot figure, because it's trying to get from `http://www.myserver.com:3000/screenshot.png` . The correct address is `http://www.myserver.com:10001/screenshot.png`.

I think it might be a bug in setting `serverURL`. How can I fix it? Thank you.
