### ISSUE TITLE
pic upload error

### ISSUE THREAD

**Issue by yw9381** [hackmdio/codimd#1309]
i set env `CMD_IMAGE_UPLOAD_TYPE=filesystem` in docker-compose file and upload pic，server return 500 error, 
docker-compose.yaml
```yaml
version: '2'
services:
  database:
      image: mariadb:10
      environment:
        - MYSQL_USER=hackmd
        - MYSQL_PASSWORD=hackmdpass
        - MYSQL_DATABASE=hackmd
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      volumes:
        - ./hackmd_data/mysql:/var/lib/mysql
        - ./mysql-utf8.cnf:/etc/mysql/conf.d/utf8.cnf
      networks:
        backend:
      restart: always
  app:
    image: hackmdio/hackmd:1.3.1
    environment:
      - HMD_DB_URL=mysql://hackmd:hackmdpass@database:3306/hackmd
      - CMD_USECDN=false
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - "3000:3000"
    networks:
      backend:
    restart: always
    depends_on:
      - database

networks:
  backend:

volumes:
  database:
```
error log
```
app_1       | 2019-10-21T10:31:49.469Z error:   uncaughtException: Invalid URL: /uploads/
app_1       | TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
app_1       |     at onParseError (internal/url.js:219:17)
app_1       |     at parse (internal/url.js:228:3)
app_1       |     at new URL (internal/url.js:311:5)
app_1       |     at new URL (internal/url.js:309:14)
app_1       |     at Object.exports.uploadImage (/codimd/lib/web/imageRouter/filesystem.js:19:19)
app_1       |     at /codimd/lib/web/imageRouter/index.js:31:22
app_1       |     at IncomingForm.<anonymous> (/codimd/node_modules/formidable/lib/incoming_form.js:107:9)
app_1       |     at emitNone (events.js:106:13)
app_1       |     at IncomingForm.emit (events.js:208:7)
app_1       |     at IncomingForm._maybeEnd (/codimd/node_modules/formidable/lib/incoming_form.js:557:8)
app_1       |     at /codimd/node_modules/formidable/lib/incoming_form.js:238:12
app_1       |     at WriteStream.<anonymous> (/codimd/node_modules/formidable/lib/file.js:79:5)
app_1       |     at Object.onceWrapper (events.js:313:30)
app_1       |     at emitNone (events.js:111:20)
app_1       |     at WriteStream.emit (events.js:208:7)
app_1       |     at finishMaybe (_stream_writable.js:613:14)
app_1       | 2019-10-21T10:31:49.470Z error:   An uncaught exception has occured.
app_1       | 2019-10-21T10:31:49.470Z error:   Invalid URL: /uploads/
app_1       | 2019-10-21T10:31:49.470Z error:   Process will exit now.
```
i check about filesystem code `/lib/web/imageRouter/filesystem.js`, line 20 to line 24
```js
  try {
    url = (new URL(path.basename(imagePath), config.serverURL + '/uploads/')).href
  } catch (e) {
    url = config.serverURL + '/uploads/' + path.basename(imagePath)
  }
```
because ` config.serverURL` is not define，so return URL is Invalid, so please fix it.
i test `image: hackmdio/hackmd:1.2.0`, this features（upload pic） is working

**Comment by a60814billy** [comment]
Hi @yw9381 
This issue has been fixed in [PR 1196](https://github.com/hackmdio/codimd/pull/1196).
Soon we will release a new version.

In 1.3.1, you can set `CMD_DOMAIN` to solve this problem.
By the way, If you use local filesystem to store your image, we recommend to set a docker volume to store your image.

```
version: "3"
services:
  database:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    image: hackmdio/hackmd:1.3.1
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database:5432/codimd
      - CMD_USECDN=false
      - CMD_DOMAIN=localhost
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/codimd/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
```
