### ISSUE TITLE
Path for picture upload not working after update to 1.4.0

### ISSUE THREAD

**Issue by MelBourbon** [hackmdio/codimd#1345]
I used 1.3.1 (docker deployment) with picture upload on filesystem by using a folder within `/docker-hackmd` called `./codimd-uploads`. I set this up in `docker-compose.yml` by using

```
environment:
      - CMD_DOMAIN=<my-url>.com
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
    volumes:
      - ./codimd-uploads:/codimd/public/uploads
```

Existing pictures are embedded  as shown below

```
![](https://<my-url>.com/uploads/upload_d29e3242173efd28b1fd80b116f057c4.jpg)
```

Now I updated to 1.4.0 (docker deployment) by using the same variables in `docker-compose.yml`. New pictures are also added as shown above **but**

* Existing uploaded pictures are not shown anymore
* New pictures are shown but not uploaded to `./codimd-uploads` anymore (checked existing of file via console)

**Comment by jackycute** [comment]
We've updated the docs for the migration! Please check if that works for you.
https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment

**Comment by MelBourbon** [comment]
Hi, I did migration as described. Had issues in between and needed to use a backup of my database. Instance is now running with the following `docker-compose.yml` but picture upload not possible and also existing pictures are now shown. How can I debug further?

```
version: "3"
services:
  database:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=<mypassword>
      - POSTGRES_DB=hackmd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:1.4.0
    environment:
      - CMD_DB_URL=postgres://hackmd:<mypassword>@database:5432/hackmd
      - CMD_USECDN=false
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_ALLOW_FREEURL=true
      - CMD_DEFAULT_PERMISSION=private
      - CMD_ALLOW_PDF_EXPORT=true
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_PROTOCOL_USESSL=false
      - CMD_HSTS_ENABLE=false
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_DOMAIN=<my-domain>
      - CMD_PROTOCOL_USESSL=true
      - CMD_URL_ADDPORT=false
    depends_on:
      - database
    ports:
      - "127.0.0.1:3000:3000"
      #- "3000:3000"
    volumes:
      - ./codimd-uploads:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
```
