### ISSUE TITLE
ver 1.4.0 connect local host?

### ISSUE THREAD

**Issue by pyama86** [hackmdio/codimd#1347]
Hi team!

I found the following log.
```
hackmd-5444ccb8bb-vqwf6 app dial tcp 127.0.0.1:80: connect: connection refused
hackmd-5444ccb8bb-vqwf6 app dial tcp 127.0.0.1:80: connect: connection refused
hackmd-5444ccb8bb-vqwf6 app dial tcp 127.0.0.1:80: connect: connection refused
hackmd-5444ccb8bb-vqwf6 app dial tcp 127.0.0.1:80: connect: connection refused
```
We use hackmd with kubernetes and apply configure below.
```
          - name: CMD_DOMAIN
            value: "hackmd.xxxxx"
          - name: CMD_DB_URL
            valueFrom:
              secretKeyRef:
                name: hackmd-secret
                key: mysql_url
          - name: CMD_PROTOCOL_USESSL
            value: "true"
          - name: CMD_URL_ADDPORT
            value: "false"
          - name: CMD_ALLOW_ANONYMOUS
            value: "false"
          - name: CMD_ALLOW_ANONYMOUS_EDITS
            value: "false"
          - name: CMD_ALLOW_FREEURL
            value: "false"
          - name: CMD_ALLOW_EMAIL_REGISTER
            value: "false"
          - name: CMD_EMAIL
            value: "false"
          - name: CMD_DEFAULT_PERMISSION
            value: "limited"
          - name: CMD_ALLOW_ANONYMOUS_VIEWS
            value: "false"
          - name: CMD_PORT
            value: "3000"
          - name: DEBUG
            value: "true"
          - name: CMD_LOG_LEVEL
            value: "debug"
```

What log is this connection connected to?

**Comment by a60814billy** [comment]
please provide more details config

1. what docker image does you uses
2. CMD_DB_URL environment variable setup correctly?
  - the format of CMD_DB_URL is `mysql://username:password@hostname:3306/hackmd_db_name`

**Comment by a60814billy** [comment]
By the way, official docker image (nabo.codimd.dev/hackmdio/hackmd:1.4.0) will check the connectivity of  CMD_DB_URL, It seems your CMD_DB_URL is incorrect

**Comment by pyama86** [comment]
Hi @a60814billy 

> what docker image does you uses

I have used hackmdio/hackmd:1.4.0.

> Is CMD_DB_URL environment variable setup correctly? (the format of CMD_DB_URL is mysql://username:password@hostname:3306/hackmd_db_name)

The item was set correctly, and it worked fine with the 1.3 series.

**Comment by dsprenkels** [comment]
I got also bit by this issue. Just like @pyama86, this regressed in version `1.4.0` in my production setup.

Sequelize still resolves correctly, but it seems that there is something going with the host resolving in the `pcheck` binary.

In my case, I have the database at `postgres://hackmd:[password]@codimd_db:5432/hackmd`. The error says:

```
# docker-compose logs codimd
codimd_1_f2179ed6361c  | dial tcp 172.21.0.3:5432: connect: connection refused
```

However, when I resolve the host from inside the container, I get a different IP address:

```
root@66ee50e8e98a:/home/hackmd/app# host codimd_db
codimd_db has address 192.168.16.2
```

**Comment by a60814billy** [comment]
portchecker not working properly caused by golang not correct use /etc/host in docker container,
related issues: https://github.com/golang/go/issues/22846

we will fix it in 1.4.1

**Comment by a60814billy** [comment]
Hi @dsprenkels and @pyama86,
We found the issue isn't the one that I attached on the above comment, that `/etc/hosts` should be parsed and resolved properly in our docker image.

This has been tested in the Docker CE 1.13, 17 on Debian Jessie, below is the `docker-compose.yml` file:

```
version: "3"
services:
  database:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:1.4.0
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database/codimd
      - CMD_USECDN=false
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
```

Also, this has been tested in Kubernetes on GCP of version 1.12, config file as follows:

```
apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: codimd-dev
type: Opaque
stringData:
  constr: mysql://hackmd:hackmdpass@mysql-svc.codimd-dev.svc:3306/hackmd?charset=utf8mb4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codi-mysql
  namespace: codimd-dev
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: hackmdpass
            - name: MYSQL_USER
              value: hackmd
            - name: MYSQL_PASSWORD
              value: hackmdpass
            - name: MYSQL_DATABASE
              value: hackmd
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: codimd-dev
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codimd
  namespace: codimd-dev
spec:
  selector:
    matchLabels:
      app: codimd
  template:
    metadata:
      labels:
        app: codimd
        version: v1
    spec:
      containers:
        - name: codi
          image: nabo.codimd.dev/hackmdio/hackmd:1.4.0
          env:
            - name: CMD_DB_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: constr
```

But all of above seems fine to me, it all can resolve the DB connection and the port checker (pchecker) is working.

Could you let me know what's your environment like the OS, k8s, docker versions and your config file? We're trying hard to reproduce this condition and to lure down this issue carefully.

Thank you!
