### ISSUE TITLE
The operation's base length must be equal to the string's length. error

### ISSUE THREAD

**Issue by jerheij** [hackmdio/codimd#1395]
Hello,

I am using codimd in docker from Linuxserver.io (version 1.3.2) and I suddenly got the error in the title of the issue when I try to edit any of my notes while they were fine the other day and nothing has really changed.

I have attempted to fix it by updating the container and changing the defaultUseHardbreak setting to false. This didn't solve it.

**docker-compose.yml:**
```
version: "3"
services:
  codimd:
    image: linuxserver/codimd:latest
    container_name: codimd
    restart: always
    volumes:
      - ./config:/config
    environment:
      - PGID=2009
      - PUID=2009
      - TZ=Europe/Amsterdam
      - CMD_DB_URL=mysql://codimd_user:supersecretpassword@db.docker.local:3306/codimd_db
    networks:
      web-int:
        ipv4_address: 192.168.188.9

networks:
  web-int:
    external: true
```

**config.json**
```
{
  "use_env_variable": "CMD_DB_URL"
}
```

**Logs:**
```
codimd    | 2020-01-30T10:10:39.093Z error:     The operation's base length must be equal to the string's length.
codimd    | 2020-01-30T10:10:40.707Z error:     The operation's base length must be equal to the string's length.
```
