### ISSUE TITLE
Using docker-compose can't use as anonymous or register

### ISSUE THREAD

**Issue by luandro** [hackmdio/codimd#1493]
Here's my `docker-compose.yml`:

```
version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=codimd
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_ALLOW_ANONYMOUS_VIEWS=true
      - CMD_DEFAULT_PERMISSION=freely
      - CMD_EMAIL=true
      - CMD_ALLOW_EMAIL_REGISTER=true
      - CMD_DOMAIN=${DOMAIN}
      - CMD_PROTOCOL_USESSL=true
      - CMD_SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.0.1
    environment:
      - CMD_DB_URL=postgres://codimd:${DB_PASS}@database/codimd
      - CMD_USECDN=false
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    depends_on:
      - database
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
networks:
  default:
    external:
      name: nginx-proxy
```

With this setup, shouldn't anonymous users be able to use normally? And shouldn't users be able to register with email?

**Comment by tarlety** [comment]
Please set CMD_* environments in the codimd container.

```yaml=
version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.0.1
    environment:
      - CMD_DB_URL=postgres://codimd:${DB_PASS}@database/codimd
      - CMD_USECDN=false
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_ALLOW_ANONYMOUS_VIEWS=true
      - CMD_DEFAULT_PERMISSION=freely
      - CMD_EMAIL=true
      - CMD_ALLOW_EMAIL_REGISTER=true
      - CMD_DOMAIN=${DOMAIN}
      - CMD_PROTOCOL_USESSL=true
      - CMD_SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - database
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
networks:
  default:
    external:
      name: nginx-proxy
```
