### ISSUE TITLE
Unauthorized users see an internal server error when creating a new freeurl pad if allow_anonymous is false

### ISSUE THREAD

**Issue by Trolldemorted** [hackmdio/codimd#1499]
Take this sample docker-compose file:
```yaml
version: '3'
services:
  database:
    # Don't upgrade PostgreSQL by simply changing the version number
    # You need to migrate the Database to the new PostgreSQL version
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - backend
  codimd:
    image: hackmdio/hackmd:latest
    environment:
      - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
      - NODE_ENV=production
      - CMD_PORT=3000
      - CMD_ALLOW_FREEURL=true
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_OAUTH2_BASEURL=https://codimd.stronk.pw
      - CMD_OAUTH2_CLIENT_ID=...
      - CMD_OAUTH2_CLIENT_SECRET=...
      - CMD_OAUTH2_AUTHORIZATION_URL=...
      - CMD_OAUTH2_TOKEN_URL=...
      - CMD_OAUTH2_USER_PROFILE_URL=...
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=uid
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=uid
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=uid
```
If I go to /foobar in a private tab, codi just says "Internal server error" and the server output is:
```
Apr 29 22:01:41 majorpurpose docker-compose[218301]: codimd_1    | Error: can not create note
Apr 29 22:01:41 majorpurpose docker-compose[218301]: codimd_1    |     at createNote (/home/hackmd/app/lib/note/index.js:38:11)
Apr 29 22:01:41 majorpurpose docker-compose[218301]: codimd_1    |     at showNote (/home/hackmd/app/lib/note/index.js:65:18)
Apr 29 22:01:41 majorpurpose docker-compose[218301]: codimd_1    |     at <anonymous>
```

Restarting codi does not resolve this issue.

cc @ldruschk
