### ISSUE TITLE
Use latest branch develop repo, local docker build is not runnable and causes exception "crypto.scrypt not found: Node.js v10.5.0+ required".

### ISSUE THREAD

**Issue by tarlety** [hackmdio/codimd#1503]
## Issue Description

I clone latest branch develop repo (with latest commit 4fd6293) and build local docker image as **codimd:develop** in the repo folder like this:

```shell
$ docker build -t codimd:develop -f deployments/Dockerfile .
```

After built I get the **codimd:develop** image:

```shell
$ docker imags
REPOSITORY                     TAG                             IMAGE ID            CREATED             SIZE
codimd                         develop                         4677d03686b0        27 minutes ago      1.77GB
```

Then I use the docker-compose.yml to test the image **codimd:develop**:

```yaml=
version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=badpassword
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    # you can use image or custom build below
    image: codimd:develop
    # build:
    #   context: ..
    #   dockerfile: ./deployments/Dockerfile
    environment:
      - CMD_DB_URL=postgres://codimd:badpassword@database/codimd
      - CMD_USECDN=false
    depends_on:
      - database
    ports:
      - "3001:3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
```

However, I get the error message like this:

```shell
$ docker-compose up
...
codimd_1    | 2020-04-30T14:00:58.301Z error:   uncaughtException: crypto.scrypt not found: Node.js v10.5.0+ required; see github.com/chrisveness/scrypt-kdf#openssl-implementation
codimd_1    | Error: crypto.scrypt not found: Node.js v10.5.0+ required; see github.com/chrisveness/scrypt-kdf#openssl-implementation
codimd_1    |     at Object.<anonymous> (/home/hackmd/app/node_modules/scrypt-kdf/scrypt.js:25:39)
codimd_1    |     at Module._compile (module.js:653:30)
codimd_1    |     at Object.Module._extensions..js (module.js:664:10)
codimd_1    |     at Module.load (module.js:566:32)
codimd_1    |     at tryModuleLoad (module.js:506:12)
codimd_1    |     at Function.Module._load (module.js:498:3)
codimd_1    |     at Module.require (module.js:597:17)
codimd_1    |     at require (internal/module.js:11:18)
codimd_1    |     at Object.<anonymous> (/home/hackmd/app/lib/models/user.js:4:14)
codimd_1    |     at Module._compile (module.js:653:30)
codimd_1    |     at Object.Module._extensions..js (module.js:664:10)
codimd_1    |     at Module.load (module.js:566:32)
codimd_1    |     at tryModuleLoad (module.js:506:12)
codimd_1    |     at Function.Module._load (module.js:498:3)
codimd_1    |     at Module.require (module.js:597:17)
codimd_1    |     at require (internal/module.js:11:18)
codimd_1    |     at Sequelize.import (/home/hackmd/app/node_modules/sequelize/lib/sequelize.js:481:62)
codimd_1    |     at /home/hackmd/app/lib/models/index.js:48:33
codimd_1    |     at Array.forEach (<anonymous>)
codimd_1    |     at Object.<anonymous> (/home/hackmd/app/lib/models/index.js:47:4)
codimd_1    |     at Module._compile (module.js:653:30)
codimd_1    |     at Object.Module._extensions..js (module.js:664:10)
```

It looks like it requires buildpack/runtime docker image to base on node 10 or above.

---

## Question

Shall develop branch upgrade node version for a runnable docker image?
Or did I miss something to cause the exception?

Thanks in advice.
