### ISSUE TITLE
Data loss in dockerize container

### ISSUE THREAD

**Issue by nanobapt** [hackmdio/codimd#1534]
Hi, 
I've been running CODIMD in a container using docker-compose.

Recently my server restart and I lost all my data inside codimd pads.

Here is my docker-compose file:
  ```
database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=xxxx
      - POSTGRES_PASSWORD=xxxx
      - POSTGRES_DB=codimd
    volumes:
      - ./pad/db-data:/var/lib/postgresql/data
    restart: always

  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.0.1
    environment:
      - CMD_DB_URL=postgres://xxxx
      - CMD_USECDN=false
      - CMD_DOMAIN=pad.xxx
      - CMD_PROTOCOL_USESSL=true
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_FREEURL=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_EMAIL=false
      - CMD_ALLOW_EMAIL_REGISTER=false
    depends_on:
      - database
    volumes:
      - ./pad/upload-data:/home/hackmd/app/public/uploads
    restart: always
```

Volume should have stored the pads content, no ?
Is there a way to restore pads content ?

Thanx
Baptiste
