### ISSUE TITLE
Am I authenticating?

### ISSUE THREAD

**Issue by paulb-opusvl** [hackmdio/codimd#1558]
Docker Image running codimd 2.2

Fresh built today and  when I authenticate I get taken to the history page and all I have is the "Sign In" button. I can't create files or do anything. It needs to not be anonymous - but I'm clearly doing something wrong.

__docker-compose.yml__
```yaml
services:
  codimd:
    depends_on:
    - db
    environment:
      CMD_ALLOW_ANONYMOUS: "false"
      CMD_ALLOW_ANONYMOUS_EDITS: "false"
      CMD_ALLOW_ANONYMOUS_VIEWS: "false"
      CMD_ALLOW_PDF_EXPORT: "true"
      CMD_DB_URL: postgres://codimd:supersecretkey@db/codimd
      CMD_DEFAULT_PERMISSION: private
      CMD_DOMAIN: 10.10.4.126:13200
      CMD_EMAIL: "true"
      CMD_LOG_LEVEL: debug
      CMD_PROTOCOL_USESSL: "false"
      CMD_SESSION_SECRET: c38de1c7e6315a20c02a2bb8eb5c3de1df06c69b
      CMD_URL_ADDPORT: "false"
      CMD_USECDN: "false"
      DEBUG: "true"
    image: nabo.codimd.dev/hackmdio/hackmd:2.2.0
    ports:
    - published: 13200
      target: 3000
    restart: always
    volumes:
    - /srv/local/container-volumes/S00132/data:/home/hackmd/app/public/uploads:rw
  db:
    environment:
      POSTGRES_DB: codimd
      POSTGRES_PASSWORD: supersecretkey
      POSTGRES_USER: codimd
    image: postgres:11.6-alpine
    restart: always
    volumes:
    - /srv/local/container-volumes/S00132/postgres:/var/lib/postgresql/data:rw
version: '3.2'
```

The account is getting created in postgres.

```sql
codimd=# select * from "Users";
                  id                  | profileid | profile | history |         createdAt          |         updatedAt          | accessToken | refreshToken |           email           |   password   |             deleteToken              
--------------------------------------+-----------+---------+---------+----------------------------+----------------------------+-------------+--------------+---------------------------+------------------------+--------------------------------------
 f74db71d-b515-46ac-bb3c-688b06fdc3b7 |           |         |         | 2020-07-20 13:06:56.886+00 | 2020-07-20 13:06:56.886+00 |             |              | paul.bargewell@opusvl.com |  *removed*   | 2874b804-3a95-4e95-a0f5-b3f2a4fbf773
(1 row)
```

Thanks in advance.
