### ISSUE TITLE
the register button is grey unavaliable

### ISSUE THREAD

**Issue by hackjackyer** [hackmdio/codimd#1560]
the register button is grey unavaliable
![QQ截图20200721164708.png](https://i.loli.net/2020/07/21/Ar9dxpGXkUSawqi.png)
my docker-compose.yml file 

```yml
version: "3"
services:
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.2.0
    environment:
      - CMD_DB_URL=mysql://root:codimd@172.17.0.1:3306/codimd
      - CMD_USECDN=false
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/opt/docker/codimd/app/public/uploads
    restart: always
volumes:
  upload-data: {}
```
