### ISSUE TITLE
GitHub OAuth URL Mismatch Error

### ISSUE THREAD

**Issue by cblessing24** [hackmdio/codimd#1617]
Hello,

I am trying to run a CodiMD server behind a SSL-enabled [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) in Docker. Everything is working except for GitHub authentication. I get "Internal server error" when trying to authenticate using GitHub and the log of the `codimd` container contains the following error message:

```AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.```

I have configured the OAuth application in Github with `https://codimd.example.com/` as the homepage url and `https://codimd.example.com/auth/github/callback` as the callback url (server name changed for privacy reasons). This is all pretty knew for me and I spent the last couple of hours debugging this without much progress. Any help would be greatly appreciated!

`docker-compose.yml`: 
```
version: "3"
services:
    proxy:
        image: jwilder/nginx-proxy
        ports:
            - "3000:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
            - "./certs:/etc/nginx/certs"
            - "./proxy.conf:/etc/nginx/proxy.conf"
        restart: always
    database:
        image: postgres:11.6-alpine
        environment:
            - POSTGRES_DB=codimd
        env_file: .db_env
        volumes:
            - "database-data:/var/lib/postgresql/data"
        restart: always
    codimd:
        image: nabo.codimd.dev/hackmdio/hackmd:2.2.0
        environment:
            - CMD_USECDN=false
        env_file: .codimd_env
        depends_on:
            - proxy
            - database
        expose:
            - "3000"
        volumes:
            - "upload-data:/home/hackmd/app/public/uploads"
        restart: always
volumes:
    database-data: {}
    upload-data: {}
```

`proxy.conf`:
```
# setup a upstream point to CodiMD server
upstream @codimd {
    server codimd:3000;
    keepalive 300;
}

# for socket.io (http upgrade)
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# redirect all http traffic to https
server {
    listen 80;
    server_name codimd.example.com;
    return 301 https://$server_name$request_uri;
}

# https server
server {
    listen 443 ssl http2;
    server_name codimd.example.com;
    
    # setup certificate
    ssl_certificate /etc/nginx/certs/kant.mvl6.uni-tuebingen.de.crt;
    ssl_certificate_key /etc/nginx/certs/kant.mvl6.uni-tuebingen.de.key;

    location / {
      proxy_http_version 1.1;
      
      # set header for proxy protocol
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      
      # setup for image upload
      client_max_body_size 8192m;
      
      # adjust proxy buffer setting
      proxy_buffers 8 32k; 
      proxy_buffer_size 32k; 
      proxy_busy_buffers_size 64k;

      proxy_max_temp_file_size 8192m;
      
      proxy_read_timeout 300;
      proxy_connect_timeout 300;
      proxy_pass http://@codimd;
    }
}
```
