### ISSUE TITLE
How to change domain?

### ISSUE THREAD

**Issue by ronald8192** [hackmdio/codimd#1705]
I use docker version of Codimd. 
Changed `CMD_DOMAIN` to my new domain, after `docker-compose restart`, the site still using the old domain. 

`docker-compose.yml`:
```yaml
version: "3"
services:
  codimd:
    image: hackmdio/hackmd:2.4.1
    environment:
      - CMD_DOMAIN=xxxxx
      - ...
```

![image](https://user-images.githubusercontent.com/5982132/126872214-d244d39a-abc3-4b54-9f73-b31a1ed1f02e.png)

**Comment by ronald8192** [comment]
I end up replacing it with a new service:
Not sure is it the only way to do it.

```yaml
version: "3"
services:
  codimd2:
    image: hackmdio/hackmd:2.4.1
    environment:
      - CMD_DOMAIN=xxxxx
      - ...
```
```
docker-compose up -d --remove-orphans
```
