### ISSUE TITLE
SAML SSO error: ACS Url in request doesn't match configured ACS Url

### ISSUE THREAD

**Issue by Jiraiya-08** [hackmdio/codimd#1713]
Hello,

First of all, i'm an apache noobie, so sorry in advance for anything stupid you might see or read... :p 

I'm trying to install a local CodiMd instance via docker on a VPS exposed publicly on the internet with a fixed IP. The Codimd server is started with Docker-compose, with SAML SSO config configured to use a Google Workspace IdP.  I have an Apache httpd server acting as reverse proxy & SSL offloader.

Besides the SAML SSO part, everything works like a charm. The backend is properly showing under codimd.example.com, the HTTP->HTTPS redirection is working fine, valid certificates etc.

### The issue:
When I click on "Sign-in" and then "Sign-in using SAML", I get correctly redirected to Google account selection screen. Then, when I select the correct account (the one from the Google Workspace domain), I get redirected to "_https://codimd.example.com/auth/saml/callback_" , with an "_Internal Server Error_" message showing on a white screen.

When I look on the logs of the docker container, I find this:
```
2021-09-06T23:21:18.485Z info: 	172.21.0.1 - - [06/Sep/2021:23:21:18 +0000] "GET /auth/saml HTTP/1.1" 302 0 "https://codimd.example.com/" "xxxxx(xxxxx) xxxxxx Chrome/93.0.4577.63 Safari/537.36"

Error: SAML provider returned Requester error: Invalid request, ACS Url in request /auth/saml/callback doesn't match configured ACS Url https://codimd.example.com/auth/saml/callback.
    at /home/hackmd/app/node_modules/passport-saml/lib/passport-saml/saml.js:677:31
    at _fulfilled (/home/hackmd/app/node_modules/passport-saml/node_modules/q/q.js:854:54)
    at /home/hackmd/app/node_modules/passport-saml/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/hackmd/app/node_modules/passport-saml/node_modules/q/q.js:816:13)
    at /home/hackmd/app/node_modules/passport-saml/node_modules/q/q.js:570:49
    at runSingle (/home/hackmd/app/node_modules/passport-saml/node_modules/q/q.js:137:13)
    at flush (/home/hackmd/app/node_modules/passport-saml/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

The thing is, on google workspace's admin console, if I go to the app's SAML config screen and I click on "Test the SAML connection" (see red rectangle on the screenshot, it redirects to the account selection screen, and then properly back to https://codimd.example.com, where I will be correctly authenticated with the Google user I selected. And then I can of course create notes etc. as I'm supposed to, without any other problem.

I don't know if that matters, but it worth noting that the HTTPD server also acts as an actual webserver for other sites configured under other domain names/virtual hosts.

I highly suspect an issue with how Apache is sending the requests back to the container, but I donc know how to solve it unfortunately.
Thanks a lot for the help!

### Here is my config:

docker-compose.yml (codymd SAML part):
```
codimd:
  image: hackmdio/hackmd:2.4.1
  environment:
    - CMD_DB_URL=postgres://codimddbuser:<password>@database/codimd
    - CMD_USECDN='false'
    - CMD_SAML_IDPSSOURL=https://accounts.google.com/o/saml2/idp?idpid=<hiddenID>
    - CMD_SAML_IDPCERT=/etc/ssl/certs/cert.pem
    - CMD_SAML_ISSUER=codimd.example.com
    - CMD_SAML_IDENTIFIERFORMAT=urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
    - CMD_SAML_ATTRIBUTE_ID=sAMAccountName
    - CMD_SAML_ATTRIBUTE_USERNAME=nickName
ports:
  - "3000:3000"
volumes:
  - upload-data:/home/hackmd/app/public/uploads
  - ./cert.pem:/etc/ssl/certs/cert.pem:ro
```

The apache config file for the virtualhost:

```
 # Redirect http to https
 <VirtualHost *:80>
     ServerName codimd.example.com
     Redirect permanent / https://codimd.example.com/
 </VirtualHost>
 
 # https
 <IfModule mod_ssl.c>
     <VirtualHost *:443>
         ServerName codimd.example.com
 
         # SSL Config
         SSLEngine on
         Include /etc/letsencrypt/options-ssl-apache.conf
         SSLCertificateFile /etc/letsencrypt/live/codimd.example.com/fullchain.pem
         SSLCertificateKeyFile /etc/letsencrypt/live/codimd.example.com/privkey.pem
         SSLProtocol all -SSLv2 -SSLv3 -TLSv1
         SSLHonorCipherOrder on
         SSLCipherSuite ALL:+HIGH:!ADH:!EXP:!SSLv2:!SSLv3:!MEDIUM:!LOW:!NULL:!aNULL
         SSLHonorCipherOrder on
 
         # Proxy websocket traffic
         RewriteEngine on
         RewriteCond %{REQUEST_URI} ^/socket.io             [NC]
         RewriteCond %{QUERY_STRING} transport=websocket    [NC]
         RewriteRule (.*)  ws://127.0.0.1:3000/$1          [P,L]
         # Proxy normal http traffic
         ProxyPass / http://127.0.0.1:3000/
         ProxyPassReverse / http://127.0.0.1:3000/
         ProxyPreserveHost on                                                                  
 
     </VirtualHost>
 </IfModule>
```

My Google Workspace SAML App config:
![codimdgoogle](https://user-images.githubusercontent.com/13663466/132265167-103f2273-cffa-424d-8353-5acfc746c616.png)
