### ISSUE TITLE
Cannot connect database when deploying with docker-compose

### ISSUE THREAD

**Issue by duskmoon314** [hackmdio/codimd#1734]
Hi, I'm trying to self-host a codimd behind traefik on my server. I come across a problem:

```
021/11/27 03:46:50 portchecker.go:42: dial tcp: lookup codimddb on 127.0.0.11:53: server misbehaving
    wait 3 seconds retry
2021/11/27 03:46:53 portchecker.go:42: dial tcp: lookup codimddb on 127.0.0.11:53: server misbehaving
    wait 3 seconds retry
2021/11/27 03:46:56 portchecker.go:42: dial tcp: lookup codimddb on 127.0.0.11:53: server misbehaving
...
```

my docker-compose.yaml

```yaml
  codimd-db:
    image: postgres:11.6-alpine
    container_name: codimddb
    restart: unless-stopped
    env_file: .postgres.codimd.env
    networks:
      - traefik-net
    ports:
      - "5434:5432"
    volumes:
      - "/data/codimd/postgres:/var/lib/postgresql/data"

  codimd:
    image: hackmdio/hackmd:2.4.1-cjk
    container_name: codimd
    env_file:
      - .codimd.env
    depends_on:
      - codimd-db
      - traefik
    ports:
      - "6001:3000"
    volumes:
      - "/data/codimd/uploads:/home/hackmd/app/public/uploads"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codimd.rule=Host(`md.$DOMAIN_NAME`)"
      - "traefik.http.services.codimd-websecure.loadbalancer.server.port=6001"
```

In env files, I set:

```
# .codimd.env
CMD_DB_URL=postgres://codimd:codimd@codimddb/codimd
CMD_USECDN=false

# .postgres.codimd.env
POSTGRES_USER=codimd
POSTGRES_PASSWORD=codimd
POSTGRES_DB=codimd
```

How can I find what is the issue and how to solve it?
