### ISSUE TITLE
Broken rendering of published note page

### ISSUE THREAD

**Issue by pnck** [hackmdio/codimd#1822]
### A test note:
![image](https://github.com/hackmdio/codimd/assets/6532324/07da0b24-d77b-4191-96c9-002734cfaddf)

Text links are correctly rendered in the preview.  
But the published version shows like this:
![image](https://github.com/hackmdio/codimd/assets/6532324/28c05c6b-6d61-4d89-990b-4821ca4430fe)

Deployed through docker:
```yaml
    image: hackmdio/hackmd:2.4.2-cjk
    environment:
      - CMD_USECDN=true
      - CMD_ALLOW_PDF_EXPORT=true
      - CMD_DOMAIN=***
      - CMD_AUTO_VERSION_CHECK=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_ALLOW_ANONYMOUSE_VIEWS=true
      - CMD_DEFAULT_PERMISSION=private
      - CMD_EMAIL=false
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_GITHUB_CLIENTID=***
      - CMD_GITHUB_CLIENTSECRET=***
      - CMD_PROTOCOL_USESSL=true
      - CMD_ALLOW_ORIGIN=['***']
      - CMD_CSP_ENABLE=true
```
