### ISSUE TITLE
Google OAuth redirect URL uses http instead of https

### ISSUE THREAD

**Issue by jakubgs** [hackmdio/codimd#972]
I'm trying to use Google OAuth and I have an Nginx proxy doing SSL in front of CodiMD like so:
```nginx
location / {
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header Host $http_host;
  proxy_set_header X-NginX-Proxy true;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_http_version 1.1;
  proxy_pass http://localhost:3000/;

  proxy_cache_bypass $http_upgrade;
  proxy_redirect off;
}
```
The problem is, when I click the button to sign in via Google I get back this:
```

400. That’s an error.
Error: redirect_uri_mismatch

The redirect URI in the request, http://codimd.my.domain/auth/google/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/xyz123qwe
```
It's clearly redirecting Google to:
```
http://codimd.my.domain/auth/google/callback
```
Instead of to:
```
https://codimd.my.domain/auth/google/callback
```
It does not seem to respect the:
```
proxy_set_header X-Forwarded-Proto $scheme;
```
setting in Nginx proxy setup.

**Comment by jakubgs** [comment]
Also, then I try to add the following settings to the container:
```
HMD_DOMAIN: 'codimd.my.domain'
HMD_PROTOCOL_USESSL: true
```
It just breaks the app UI which becomes unresponsive like so:

![codimd_broken](https://user-images.githubusercontent.com/2212681/46213220-01125980-c306-11e8-9ef1-fa0e97904ca0.png)

**Comment by jakubgs** [comment]
I see this might be related: https://github.com/hackmdio/codimd/issues/319

**Comment by jakubgs** [comment]
According to the documentation for `HMD_PROTOCOL_USESSL`:
>set to use SSL protocol for resources path (only applied when domain is set)

But when I do set the `HMD_DOMAIN` variable it breaks the UI as shown above.

**Comment by jakubgs** [comment]
OH! I see, the secret sauce is setting also:
```
CMD_URL_ADDPORT: false
```
This fixes some things, but not all, since some are requested from HTTP:

Some examples:
```
http://codimd.my.domain/build/font.5e472e42fa170fb8fdc6.css
http://codimd.my.domain/build/cover.5e472e42fa170fb8fdc6.css
http://codimd.my.domain/config
http://codimd.my.domain/build/7.cover.5e472e42fa170fb8fdc6.js
http://codimd.my.domain/favicon.png
```
And OAuth callback still uses HTTP.

**Comment by jakubgs** [comment]
I'm using all 3 of these settings and it's broken:
```yaml
HMD_DOMAIN: 'codimd.my.domain'
HMD_URL_ADDPORT: false
HMD_PROTOCOL_USESSL: true
```

**Comment by jakubgs** [comment]
BTW, I'm using the image from https://hub.docker.com/r/hackmdio/hackmd/tags/ tagged as `1.2.0`.

**Comment by SISheogorath** [comment]
First of all: Please keep in mind that this is an issue tracker, not a live ticker. And everyone who watches this repo (~150 people) gets an email for **each** of your comments. So when you search for interactive help, please visit our **support and community channel [`#codimd:matrix.org]`(https://matrix.to/#/#codimd:matrix.org)**

Then again: Your configs are correct. Make sure you recreated your container with these latest 3 settings set. This is how callback with a reverse proxy become HTTPS. And yes, this is tested on a regular basis and not broken since there were no recent changes on our side.

**Comment by jakubgs** [comment]
Sorry for the spam, I wasn't trying to solicit help, just documment my progress, next time I'll just edit my first post to avoid that.
I've been removing the container every time to verify I've changed these settings.
Does the `HMD_DOMAIN` setting just affect how the app work or does it also change anything in the database? Every time I add it there are a few resources that are still attempted to be loaded from `http`, which suggests to me that the fact  created the container without `https` setup first might cause this, but not sure.

**Comment by SISheogorath** [comment]
`CMD_DOMAIN` or `HMD_DOMAIN` only affects the app. When you have http links in your notes, they will not change.

Can you share you docker-compose file without your secrets so I can try to reproduce your problem?

**Comment by jakubgs** [comment]
I'm using ansible:
```yaml
- name: 'Create {{ cont_name }} container'
  docker_container:
    name: '{{ cont_name }}'
    image: '{{ cont_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    links:
      - '{{ db_cont_name }}:database'
    ports:
      - '{{ cont_port }}:{{ cont_port }}'
    env:
      DEBUG: false
      HMD_DB_URL: 'postgres://{{ hackmd_db_user }}:{{ hackmd_db_pass }}@database:{{ db_cont_port }}/{{ hackmd_db_name }}'
      HMD_DOMAIN: '{{ hackmd_domain }}'
      HMD_URL_ADDPORT: false
      HMD_PROTOCOL_USESSL: true
      HMD_EMAIL: false
      HMD_ALLOW_EMAIL_REGISTER: false
      HMD_ALLOW_FREEURL: true
      HMD_ALLOW_ANONYMOUS: false
      HMD_ALLOW_PDF_EXPORT: true
      HMD_IMAGE_UPLOAD_TYPE: filesystem
      HMD_DEFAULT_PERMISSION: limited
      HMD_GOOGLE_CLIENTID: '{{ hackmd_oauth_id }}'
      HMD_GOOGLE_CLIENTSECRET: '{{ hackmd_oauth_secret }}'
    volumes:
      - '/docker/{{ cont_name }}/uploads:/hackmd/public/uploads'
```
And my proxy config right now is:
```nginx
listen 443 ssl

server_name {{ hackmd_domain }}

ssl_certificate     /certs/origin.crt
ssl_certificate_key /certs/origin.key

location / {
  proxy_pass http://localhost:{{ cont_port }}/;
  proxy_set_header X-NginX-Proxy true;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Host $host;
  proxy_http_version 1.1;
  proxy_redirect off;
}
```
